Bilet.PL/Models/cSepet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bilet.PL.Models
{
    public class cSepet
    {
        public int KoltukNo { get; set; }
        

        public static List<cSepet> SepetAl()
        {
            HttpContext context = HttpContext.Current;
            if (context.Session["sepet"] == null)
                context.Session["sepet"] = new List<cSepet>();

            return (List<cSepet>)context.Session["sepet"];
        }
        public void SepeteEkle(List<cSepet> sepet, cSepet siparis)
        {
            if (sepet.Any(x => x.KoltukNo == siparis.KoltukNo))
            {
                //ürün daha önceden sepete atılmışsa...
                foreach (cSepet item in sepet)
                {
                    if (item.KoltukNo == siparis.KoltukNo)
                    {

                    }
                }
            }
            else
            {
                //ürün ilk defa sepete atılıyorsa...
                sepet.Add(siparis);
            }
            HttpContext.Current.Session["sepet"] = sepet;
            HttpContext.Current.Session["toplamadet"] = ToplamAdet(sepet);
            //HttpContext.Current.Session["toplamtutar"] = ToplamTutar(sepet);
        }
        public void SepettenSil(List<cSepet> sepet, cSepet siparis)
        {
            sepet.Remove(siparis);
            HttpContext.Current.Session["sepet"] = sepet;
            HttpContext.Current.Session["toplamadet"] = ToplamAdet(sepet);
            //HttpContext.Current.Session["toplamtutar"] = ToplamTutar(sepet);
        }
        public int ToplamAdet(List<cSepet> sepet)
        {
            return sepet.Count();
        }
        //public decimal ToplamTutar(List<cSepet> sepet)
        //{
        //    decimal TopTutar = 0;
        //    foreach (cSepet koltuk in sepet)
        //    {
        //        TopTutar += koltuk.fiyat;
        //    }
        //    return TopTutar;
        //}
    }
}

Bilet.PL/Controllers/BaseController.cs
using Bilet.BLL.Repository;
using Bilet.DAL.Context;
using Bilet.Entity.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bilet.PL.Controllers
{
    public class BaseController : Controller
    {
        BiletContext ent = new BiletContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            Repository<Guzergah> repoG = new Repository<Guzergah>(ent);
            ViewBag.Guzergahlar = repoG.GetAll();
            Repository<KalkisYeri> repoY = new Repository<KalkisYeri>(ent);
            ViewBag.KalkisYerler = repoY.GetAll();
            Repository<Destinasyon> repoD = new Repository<Destinasyon>(ent);
            ViewBag.Destinasyonlar = repoD.GetAll();
            Repository<BiletSatisDetay> repoK = new Repository<BiletSatisDetay>(ent);
            ViewBag.BiletSatisDetaylar = repoK.GetAll();

            //Repository<Tag> repoT = new Repository<Tag>(ent);
            //ViewBag.Etiketler = repoT.GetAll(null, t => t.OrderByDescending(x => x.Articles.Count)).Take(5);

            base.OnActionExecuting(filterContext);
        }

    }
}

Bilet.PL/Controllers/BiletController.cs
using Bilet.BLL.Repository;
using Bilet.DAL.Context;
using Bilet.Entity.Entity;
using Bilet.PL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bilet.PL.Controllers
{
    public class BiletController : BaseController
    {
        BiletContext ent = new BiletContext();
        // GET: Bilet
        public ActionResult Index()
        {
            
            return View();
        }
        [HttpGet]
        public JsonResult DestinasyonGetir(int KalkisYerId)
        {
            return Json(ent.Guzergahlar.Where(s => s.KalkisYeriId == KalkisYerId).Select(s => new
            {
                Id = s.DestinasyonId,
                Destinasyon = s.Destinasyon.DestinasyonYer
            }).ToList(), JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult TarihGetir(int KalkisYerId , int DestinasyonId)
        {
            return Json(ent.Seferler.Where(t => t.Guzergah.KalkisYeriId == KalkisYerId && t.Guzergah.DestinasyonId==DestinasyonId).Select(t => new
            {
                Id = t.Id,
                KalkisTarihi = t.KalkisTarihi
            }).ToList(), JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult SaatGetir(int KalkisYerId, int DestinasyonId , int SeferId)
        {
            return Json(ent.SeferSaatler.Where(s => s.Sefer.Guzergah.KalkisYeriId == KalkisYerId && s.Sefer.Guzergah.DestinasyonId == DestinasyonId && s.SeferId==SeferId).Select(s => new
            {
                Id = s.Id,
                KalkisSaati = s.KalkisSaati
            }).ToList(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult KoltukSec(int SeferSaatId)
        {
            SeferSaat secilen = (from c in ent.SeferSaatler
                              where c.Id == SeferSaatId
                              select c).FirstOrDefault();

            return View(secilen);
        }
        [HttpGet]
        public ActionResult SecilenKoltuk(List<int> KoltukNolar)
        {
            //BiletSatisDetay bd = ent.BiletSatisDetaylar.Where(b => b.KoltukNo == KoltukNo).FirstOrDefault();
            foreach (var KoltukNo in KoltukNolar)
            {
                cSepet secilen = new cSepet();
                secilen.KoltukNo = KoltukNo;

                List<cSepet> sepet = cSepet.SepetAl();
                secilen.SepeteEkle(sepet, secilen);
            }
           
            return RedirectToAction("Odemeler");
            
        }
        public ActionResult Odemeler()
        {
            return View();
        }
        //[HttpPost]
        //public ActionResult KoltukSec(List<int> KoltukNumaralar)
        //{
        //    Product degisen = (from c in ent.Products
        //                       where c.Id == Degismis.Id
        //                       select c).FirstOrDefault();
        //    degisen.ProductName = Degismis.ProductName;
        //    degisen.Price = Degismis.Price;
        //    degisen.UnitsInStock = Degismis.UnitsInStock;
        //    degisen.CategoryId = Degismis.CategoryId;

        //    ent.SaveChanges();
        //    return RedirectToAction("Index");
        //}
    }
}

Bilet.PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bilet.PL.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bilet.PL/Views/Bilet/Index.cshtml
@model Bilet.Entity.Entity.Guzergah

@{
    ViewBag.Title = "Index";
}

<head>
    <title>Flight Ticket Booking a Flat Responsive Widget Template :: w3layouts</title>
    <link rel="stylesheet" href="~/css/style2.css">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300italic,300,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Flight Ticket Booking  Widget Responsive, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"
            integrity="sha256-iBcUE/x23aI6syuqF7EeT/+JFBxjPs5zeFJEXxumwb0="
            crossorigin="anonymous"></script>
</head>
<!-- banner -->
<section class="banner_inner" id="home">
    <div class="banner_inner_overlay">
    </div>
</section>
<!-- //banner -->

<body>
    <h1>Şehirlerarası Otobüs Bileti Al</h1>
    <div class="main-agileinfo">
        <div class="sap_tabs">
            <div id="horizontalTab">
                <ul class="resp-tabs-list">
                    <li class="resp-tab-item"><span>Sefer Bilgileri</span></li>
                </ul>
                <div class="clearfix"> </div>
                <div class="resp-tabs-container">

                    <div class="tab-1 resp-tab-content oneway">
                        <form action="#" method="post">
                            <div class="from">
                                <h3>Nereden?</h3>

                                <select id="cbKalkisYerleri">
                                    <option value="-1">Kalkış yeri Seçiniz.</option>
                                    @foreach (var ky in ViewBag.KalkisYerler)
                                    {
                                        <option value="@ky.Id">@ky.KalkisYer</option>
                                    }
                                </select>
                            </div>
                            <div class="to">
                                <h3>Nereye?</h3>
                                <select id="cbDestinasyonlar"></select>

                            </div>
                            <div class="clear"></div>
                            <div class="date">
                                <div class="depart">
                                    <h3>Ne Zaman?</h3>
                                    <select id="cbKalkisTarihleri"></select>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="class">
                                <h3>Saat Kaçta?</h3>
                                <select id="cbKalkisSaatleri"></select>
                            </div>                          
                            <div class="clear"></div>                           
                            <a id="ks" >Koltuk Seç</a>                           
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-w3l">
        <p class="agileinfo"> &copy; 2016 Flight Ticket Booking . All Rights Reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
    </div>
    <!--script for portfolio-->
    <!--kalkış yerine göre destinasyon seçimi-->
    <script type="text/javascript">
        $(document).ready(function () {
            $("#cbKalkisYerleri").on('change', function () {
                console.log("change");
                var KalkisYeriId = $('#cbKalkisYerleri option:selected').val();
                console.log(KalkisYeriId);
                $.ajax({
                    type: 'GET',
                    data: { KalkisYerId: KalkisYeriId },
                    url: "/Bilet/DestinasyonGetir",
                    success: function (result) {
                        //var destinasyonlar = JSON.parse(result);
                        var s = '<option value="-1">Destinasyon Seçiniz.</option>';
                        for (var i = 0; i < result.length; i++) {
                            s += '<option value="' + result[i].Id + '">' + result[i].Destinasyon + '</option>'
                        }
                        $('#cbDestinasyonlar').html(s);
                    }

                });
            });
        });
    </script>
    <!--kalkış yerine göre destinasyon seçimi-->
    <!--sefere göre tarih seçimi-->
    <script type="text/javascript">
        $(document).ready(function () {
            $("#cbDestinasyonlar").on('change', function () {
                console.log("change");
                var KalkisYeriId = $('#cbKalkisYerleri option:selected').val();
                var DestinasyonId = $('#cbDestinasyonlar option:selected').val();
                console.log(KalkisYeriId);
                $.ajax({
                    type: 'GET',
                    data: { KalkisYerId: KalkisYeriId, DestinasyonId: DestinasyonId },
                    url: "/Bilet/TarihGetir",
                    success: function (result) {
                        //var destinasyonlar = JSON.parse(result);
                        var s = '<option value="-1">Kalkış Tarihi Seçiniz.</option>';
                        for (var i = 0; i < result.length; i++) {
                            s += '<option value="' + result[i].Id + '">' + result[i].KalkisTarihi + '</option>'
                        }
                        $('#cbKalkisTarihleri').html(s);
                    }

                });
            });
        });
    </script>
    <!--sefere göre tarih seçimi-->
    <!--tarihe göre saat seçimi-->
    <script type="text/javascript">
        $(document).ready(function () {
            $("#cbKalkisTarihleri").on('change', function () {
                console.log("change");
                var KalkisYeriId = $('#cbKalkisYerleri option:selected').val();
                var DestinasyonId = $('#cbDestinasyonlar option:selected').val();
                var SeferId = $('#cbKalkisTarihleri option:selected').val();
                console.log(KalkisYeriId);
                $.ajax({
                    type: 'GET',
                    data: { KalkisYerId: KalkisYeriId, DestinasyonId: DestinasyonId, SeferId: SeferId },
                    url: "/Bilet/SaatGetir",
                    success: function (result) {
                        //var destinasyonlar = JSON.parse(result);
                        var s = '<option value="-1">Kalkış Saati Seçiniz.</option>';
                        for (var i = 0; i < result.length; i++) {
                            s += '<option value="' + result[i].Id + '">' + result[i].KalkisSaati + '</option>'
                        }
                        $('#cbKalkisSaatleri').html(s);
                    }

                });
            });
        });
    </script>
    <!--tarihe göre saat seçimi-->
    <!--Kalkis Saate göre button enable etme-->
    <script type="text/javascript">
        //var degisecek = document.querySelector("#cbOtobusler");
        //var aktiflik = document.querySelector('#ks');
        //degisecek.onchange = function () {
        //    aktiflik.removeAttribute('disabled');
        //};
        var OId;
        $("#cbKalkisSaatleri").on('change', function () {
            console.log("change");
            SId = $('#cbKalkisSaatleri option:selected').val();
            console.log(OId);
            var ksstring = "/Bilet/KoltukSec/?SeferSaatId=" + SId;
            console.log(ksstring);
            $("#ks").attr("href", ksstring);
            $("#ks").attr("class", "btn btn-primary");

        });
        console.log(SId);

    </script>
    <!--otobüse göre button enable etme-->

    <script src="js/jquery.min.js"></script>
    <script src="js/easyResponsiveTabs.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#horizontalTab').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion
                width: 'auto', //auto or any width like 600px
                fit: true   // 100% fit in a container
            });
        });
    </script>
    <!--//script for portfolio-->
    <!-- Calendar -->
    <link rel="stylesheet" href="css/jquery-ui.css" />
    <script src="js/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker,#datepicker1,#datepicker2,#datepicker3").datepicker();
        });
    </script>
    <!-- //Calendar -->
    <!--quantity-->
    <!--//quantity-->
    <!--load more-->
    <!-- //load-more -->





</body>

Bilet.PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<!-- banner -->
<section class="banner_inner" id="home">
    <div class="banner_inner_overlay">
    </div>
</section>
<!-- //banner -->
<!-- Contact -->
<section class="contact py-5">
    <div class="container py-lg-5 py-sm-3">
        <h2 class="heading text-capitalize text-center mb-sm-5 mb-4"> Get In Touch with us</h2>
        <ul class="list-unstyled row text-center mt-lg-5 mt-4 px-lg-5">
            <li class="col-md-4 col-sm-6 adress-w3pvt-info">
                <div class=" adress-icon">
                    <span class="fa fa-map-marker"></span>
                </div>

                <h6>Location</h6>
                <p>
                    The company name
                    <br>Addison Township, IL, USA.
                </p>
            </li>

            <li class="col-md-4 col-sm-6 adress-w3pvt-info mt-sm-0 mt-4">
                <div class="adress-icon">
                    <span class="fa fa-envelope-open-o"></span>
                </div>
                <h6>Phone & Email</h6>
                <p>+(122) 123 456 7890</p>
                <a href="mailto:info@example.com" class="mail">info@examplemail.com</a>
            </li>
            <li class="col-md-4 col-sm-6 adress-w3pvt-info mt-md-0 mt-4">

                <div class="adress-icon">
                    <span class="fa fa-comments-o"></span>
                </div>

                <h6>Stay In Touch</h6>
                <ul class="social_section_1info mt-2">
                    <li class="mb-2 facebook"><a href="#"><span class="fa fa-facebook"></span></a></li>
                    <li class="mb-2 twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
                    <li class="google"><a href="#"><span class="fa fa-google-plus"></span></a></li>
                    <li class="linkedin"><a href="#"><span class="fa fa-linkedin"></span></a></li>
                </ul>
            </li>
        </ul>

        <div class="contact-grids mt-5">
            <div class="row">
                <div class="col-lg-6 col-md-6 contact-left-form">
                    <form action="#" method="post">
                        <div class=" form-group contact-forms">
                            <input type="text" class="form-control" placeholder="Name" required="">
                        </div>
                        <div class="form-group contact-forms">
                            <input type="email" class="form-control" placeholder="Email" required="">
                        </div>
                        <div class="form-group contact-forms">
                            <input type="text" class="form-control" placeholder="Phone" required="">
                        </div>
                        <div class="form-group contact-forms">
                            <textarea class="form-control" placeholder="Message" rows="3" required=""></textarea>
                        </div>
                        <button class="btn btn-block sent-butnn">Send</button>
                    </form>
                </div>
                <div class="col-lg-6 col-md-6 contact-right pl-lg-5">
                    <h4>Do you have any questions about us? write to us.</h4>
                    <p class="mt-md-4 mt-2">
                        Duis nisi sapien, elementum finibus fermentum eget, aliquet et leo. Mauris hendrerit vel ex.
                        Quisque vitae luctus massa. Phas ellus sed aliquam leo. Vestibulum ullamcorper massa eut sed fringilla. Integer ultrices finibus sed nisi.
                        in convallis felis da bus sit amet  aliquet et leo dolor sit amet aliquet.
                    </p>
                    <h5 class="mt-lg-5 mt-3">Office Hours</h5>
                    <p class="mt-3">Monday to Friday : 09 am to 06 pm</p>
                    <p>Saturday and Sunay : 10 am to 04 pm</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- //Contact -->
<!-- map -->
<div class="map p-2">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d158857.728106568!2d-0.24168153701090248!3d51.52877184090542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8a00baf21de75%3A0x52963a5addd52a99!2sLondon%2C+UK!5e0!3m2!1sen!2sin!4v1544074523717"></iframe>
</div>
<!-- //map -->

Bilet.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Bilet.PL/Views/Shared/_LayoutBilet.cshtml
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Grand Tour Travel Category Flat Bootstrap Responsive Web Template | Home :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Grand Tour Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <!-- css files -->
    <link href="/css/bootstrap.css" rel='stylesheet' type='text/css' /><!-- bootstrap css -->
    <link href="/css/style.css" rel='stylesheet' type='text/css' /><!-- custom css -->
    <link href="/css/font-awesome.min.css" rel="stylesheet"><!-- fontawesome css -->
    <!-- //css files -->

    <link href="/css/css_slider.css" type="text/css" rel="stylesheet" media="all">

    <!-- google fonts -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- //google fonts -->

</head>
<body>

    <!-- header -->
    <header>
        <div class="container">
            <!-- nav -->
            <nav class="py-md-4 py-3 d-lg-flex">
                <div id="logo">
                    <h1 class="mt-md-0 mt-2"> <a href="index.html"><span class="fa fa-map-signs"></span> Karabay Turizm </a></h1>
                </div>
                <label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
                <input type="checkbox" id="drop" />
                <ul class="menu ml-auto mt-1">
                    <li class="active">@Html.ActionLink("Anasayfa", "Index", "Home")</li>
                    <li class="">@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                    <li class=""><a href="services.html">Servisler</a></li>
                    <li class=""><a href="packages.html">Paketler</a></li>
                    <li class="">@Html.ActionLink("İletişim", "Contact", "Home")</li>
                    <li class="booking">@Html.ActionLink("Bilet Al", "Index", "Bilet")</li>
                </ul>
            </nav>
            <!-- //nav -->
        </div>
    </header>
    <!-- //header -->
    <!-- banner -->
    <div id="content1">
        @RenderBody()
    </div>
    <!-- //banner -->
    <!-- about -->
    
    <!-- //about -->
    <!-- how to book -->
    
    <!-- //how to book -->
    <!-- tour packages -->
    
    <!-- tour packages -->
    <!-- text -->
    
    <!-- //text -->
    <!-- destinations -->
    
    <!-- destinations -->
    <!--footer -->
    <footer>
        <section class="footer footer_w3layouts_section_1its py-5">
            <div class="container py-lg-4 py-3">
                <div class="row footer-top">
                    <div class="col-lg-3 col-sm-6 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Address</h3>
                        </div>
                        <div class="footer-text">
                            <p>Location : 1234 lock, Charlotte, North Carolina, United States</p>
                            <p>Phone : +12 534894364</p>
                            <p>Email : <a href="mailto:info@example.com">info@example.com</a></p>
                            <p>Fax : +12 534894364</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 footer-grid_section mt-sm-0 mt-4">
                        <div class="footer-title">
                            <h3>About Us</h3>
                        </div>
                        <div class="footer-text">
                            <p>
                                Vivamus magna justo, laci niats eget consectetur sed, conval lis at tellus. Nulla quis lorem ipnt libero.
                                Lorem ipsum dolor.
                            </p>
                        </div>
                        <ul class="social_section_1info">
                            <li class="mb-2 facebook"><a href="#"><span class="fa fa-facebook"></span></a></li>
                            <li class="mb-2 twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
                            <li class="google"><a href="#"><span class="fa fa-google-plus"></span></a></li>
                            <li class="linkedin"><a href="#"><span class="fa fa-linkedin"></span></a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Travel Places</h3>
                        </div>
                        <div class="row">
                            <ul class="col-6 links">
                                <li><a href="#choose" class="scroll">New Zealand </a></li>
                                <li><a href="#overview" class="scroll">Paris, France </a></li>
                                <li><a href="#pricing" class="scroll">Los Angles</a></li>
                                <li><a href="#faq" class="scroll"> Darlington</a></li>
                                <li><a href="#testimonials" class="scroll">Canada </a></li>
                                <li><a href="#contact" class="scroll"> South Africa </a></li>
                            </ul>
                            <ul class="col-6 links">
                                <li><a href="#">Spain </a></li>
                                <li><a href="#">Turkey </a></li>
                                <li><a href="#faq" class="scroll">Europe </a></li>
                                <li><a href="#">Italy </a></li>
                                <li><a href="#">Sweden </a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Newsletter</h3>
                        </div>
                        <div class="footer-text">
                            <p>By subscribing to our mailing list you will always get latest news and updates from us.</p>
                            <form action="#" method="post">
                                <input type="email" name="Email" placeholder="Enter your email..." required="">
                                <button class="btn1"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                                <div class="clearfix"> </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </footer>
    <!-- //footer -->
    <!-- copyright -->
    <div class="copyright py-3 text-center">
        <p>© 2019 Grand Tour. All Rights Reserved | Design by <a href="http://w3layouts.com/" target="=_blank"> W3layouts </a></p>
    </div>
    <!-- //copyright -->
    <!-- move top -->
    <div class="move-top text-right">
        <a href="#home" class="move-top">
            <span class="fa fa-angle-up  mb-3" aria-hidden="true"></span>
        </a>
    </div>
    <!-- move top -->


</body>
</html>